name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          npm install
          npx tree-sitter build-wasm node_modules/tree-sitter-python
          node index.js || true
      - uses: actions/upload-artifact@v2
        with:
          name: tree-sitter-python.wasm
          path: tree-sitter-python.wasm
